apiVersion: skaffold/v3
kind: Config
metadata:
  name: logmower-eventsource

build:
  artifacts:
  - image: harbor.k-space.ee/eaas/logmower-eventsource
    docker:
      dockerfile: Dockerfile

deploy:
  kubectl: {}

manifests:
  rawYaml:
     - k8s/staging/deployment.yaml

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        - image: harbor.k-space.ee/eaas/logmower-eventsource
          docker:
            target: prod
          sync:
            manual:
              - src: '*.js'
                dest: .
    portForward:
      - resourceType: deployment
        resourceName: logmower-eventsource
        port: 9229
        localPort: 9229
    manifests:
      rawYaml:
        - k8s/dev/deployment-camtiler.yaml
